name: Android Build

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Write premission for Gradlew
        run: chmod +x ./gradlew
      - name: Set Up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build Dev Application
        run: ./gradlew build
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v2
        with:
          name: devDebug Application
          path: ./app/build/outputs/apk/debug/app-debug.apk

      - name: send default message
        uses: appleboy/telegram-action@master
        with:
          to: ${{TELEGRAM_TO_DEBUG}}
          token: ${{TELEGRAM_TOKEN_DEBUG}}
          message: Est' dva stula, na odnom devops, na drugom algosiki
          document: main.out